### PR TITLE
Propose the correct link to supple mat

### PR DESCRIPTION
**Pull request by xuhuifan**
Dear Editors, 
The previous link for the supple material of the Binary Space Partitioning-Tree process is not correct. This is the correct link to the supplementary material of the Binary Space Partitioning-Tree Process. 
Thanks, 
Xuhui

### CODE REVIEW

**Review by lawrennd — COMMENTED** [review]
This change doesn't fix the error which seems to be in the naming of the PDF file.

**Comment by lawrennd** [comment]
Hi @xuhuifan 
Thanks for submitting!

The error appears to be with the naming of the supplementary material, rather than the link naming here. 

I've swapped the names of fan18a-supp and fan18b-supp to make a first fix, but it's not clear to me that fan18a-supp is genuinely supplementary material, I'll email Fernando and Amos to check.

Neil

**Comment by amosstorkey** [comment]
Due to the wonderful axing of cmt2 probably in response to GDPR we no longer have access to anything wrt AISTATS submissions, so it is hard for us to check what was on the system (without bugging CMT support for the details).

But my reading of 

http://proceedings.mlr.press/v84/fan18b/fan18b-supp.pdf

suggests this is indeed supplementary material (various justifications and proofs).

Amos

**Comment by xuhuifan** [comment]
Hi Neil and Amos, 

I am the author of the paper and I can verify this is the submitted supplementary material to the paper. 
Thanks for your kind help. 

Xuhui

**Comment by lawrennd** [comment]
Thanks Xuhui!

**Pull request closed without merging**
