### PR TITLE
Update 2018-03-31-murray18a.md

### PR DESCRIPTION
**Pull request by dlunde**
Fixed incorrect spelling of my last name.

Cheers,
Daniel Lundén

### CODE REVIEW

**Comment by lawrennd** [comment]
Thanks Daniel!

**Comment by dlunde** [comment]
Hi again @lawrennd

Any reason why this wasn't merged?

Cheers,
Daniel

**Review by lawrennd — COMMENTED** [review]
CHanges are fine.

**Comment by lawrennd** [comment]
Unsure .. may have been an incorrect button press (close instead of merge) on my behalf. But I can't merge now though because you've deleted the repository your end. I'll make the change directly.

**Comment by lawrennd** [comment]
Hi @dlunde, 

Apologies, the changes had been merged, but there was another error in the site that prevented them from displaying on the webpage, thanks for highlighting this!

Neil

**Comment by dlunde** [comment]
No problem, thanks!

Cheers,
Daniel

**Pull request closed without merging**
