### PR TITLE
mitrovic18a corrected files.

### PR DESCRIPTION
**Pull request by mmitrovi**
Re-added references to main file and added supplementary file.

### CODE REVIEW

**Comment by lawrennd** [comment]
Hi,

You ned to be clearer about what was done and why before I accept the pull request. Have you updated your submission files? If so did you have permission from the proceedings editors? Can you forward that to this thread and explain why the update was needed?

Once that's all in place I can assimilate the changes by accepting the pull request.

Neil

**Comment by mmitrovi** [comment]
Hi Neil,

I apologize for not being more specific. Basically the main version of our
paper that was uploaded was missing the references, and the supplementary
material wasn't available at all. All I did was re-upload the main version
with the references (mitrovic18a.pdf) and then also upload the
supplementary material (mitrovic18a-supp.pdf).

I spoke with Chloe-Agathe Azencott and she gave me the instructions for
what to do. I will forward you that thread to this same email.

Please let me know if there is anything else I need to do or explain,

All the best,

Marko

**Comment by mmitrovi** [comment]
Here is the email thread with Chloe.

---------- Forwarded message ----------
From: Marko Mitrovic <marko.mitrovic@yale.edu>
Date: Thu, May 3, 2018 at 12:02 PM
Subject: Re: Problem with Published Version of Paper
To: Chloe-Agathe Azencott <chloe-agathe.azencott@mines-paristech.fr>


Hi Chloe,

Ok, I think I did it :)

Please let me know if I made a mistake somewhere or if there is anything
else I need to do.

Thank you again for your help,

Marko

**Comment by lawrennd** [comment]
Thanks Marko! It's just so that we keep a thread of how/why proceedings have changed!

Neil

**Pull request merged**
